// Code generated by github.com/taniiicom/elasticsearch2go. DO NOT EDIT.
// Code generated by github.com/taniiicom/elasticsearch2go. DO NOT EDIT.
// Code generated by github.com/taniiicom/elasticsearch2go. DO NOT EDIT.

package searchmodel

import "time"

type CafeDocJson struct {
	Address *string `json:"address"`
	AverageRating *float64 `json:"average_rating"`
	CafeName *string `json:"cafe_name"`
	DateAdded *time.Time `json:"date_added"`
	Location []float64 `json:"location"`
	MenuItems *MenuItems `json:"menu_items"`
	PhoneNumber *string `json:"phone_number"`
	ReviewCount *uint64 `json:"review_count"`
	Website *string `json:"website"`
}

type MenuItems struct {
	Category *string `json:"category"`
	Items *Items `json:"items"`
}

type Items struct {
	Available bool `json:"available"`
	Ingredients *string `json:"ingredients"`
	ItemName *string `json:"item_name"`
	Price *float64 `json:"price"`
	Size *string `json:"size"`
}

